services:
  server:
    build:
      dockerfile: ./backend/backend.Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - .\backend\:/app/
    depends_on:
      - postgres
  pinger:
    build:
      dockerfile: ./pinger/pinger.Dockerfile
    volumes:
      - .\pinger\:/app/
    depends_on:
      - postgres
      - server
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - '5432:5432'
  frontend:
    build:
      dockerfile: ./frontend/frontend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .\frontend\:/app/
    depends_on:
      - postgres
      - server